import {
  Amana,
  ImageFrame01,
  ImageFrame02,
  ImageFrame03,
  ImageFrame04,
} from "./images";

export const OurTeam = [
  {
    image: Amana,
    imageFrame: ImageFrame01,
    name: "Amanda Fisher",
    title: "Insert your title here",
    about: "There are many variations of passages of Lorem Ipsum available",
    twitter: "",
    linkedin: "",
    mail: "",
  },
  {
    image: Amana,
    imageFrame: ImageFrame02,
    name: "Amanda F2",
    title: "Insert your title here",
    about: "There are many variations of passages of Lorem Ipsum available",
    twitter: "",
    linkedin: "",
    mail: "",
  },
  {
    image: Amana,
    imageFrame: ImageFrame01,
    name: "Amanda F3",
    title: "Insert your title here",
    about: "There are many variations of passages of Lorem Ipsum available",
    twitter: "",
    linkedin: "",
    mail: "",
  },
  {
    image: Amana,
    imageFrame: ImageFrame03,
    name: "Amanda F4",
    title: "Insert your title here",
    about: "There are many variations of passages of Lorem Ipsum available",
    twitter: "",
    linkedin: "",
    mail: "",
  },
  {
    image: Amana,
    imageFrame: ImageFrame04,
    name: "Amanda F5",
    title: "Insert your title here",
    about: "There are many variations of passages of Lorem Ipsum available",
    twitter: "",
    linkedin: "",
    mail: "",
  },
];
